name: .NET

on:
  push:
    branches: [ "master" ]

env:
  PACKAGE_PATH: /home/runner/work/s7-01-csharp-react/s7-01-csharp-react/bin/Release/net6.0/publish
  CONFIGURATION: Release
  WORKING_DIRECTORY: .
  DONWLOADED_PACK:  /home/runner/work/s7-01-csharp-react/s7-01-csharp-react
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish  --configuration ${{ env.CONFIGURATION }} --no-build
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: "${{ env.PACKAGE_PATH }}"
        

