name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  PACKAGE_PATH: /home/runner/work/s7-01-csharp-react/s7-01-csharp-react/bin/Release/net6.0/publish
  CONFIGURATION: Release
  WORKING_DIRECTORY: .
  DONWLOADED_PACK:  /home/runner/work/s7-01-csharp-react/s7-01-csharp-react
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish  --configuration ${{ env.CONFIGURATION }} --no-build
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: "${{ env.PACKAGE_PATH }}"
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: "${{ env.WORKING_DIRECTORY }}"
        
    - name: Upload from public_html via FTP
      uses: airvzxf/ftp-deployment-action@latest
      with:
         server: 155.254.244.28
         user: danto
         password: ${{ secrets.SOMEE_URL_FTP_SERVER_PASSWORD }}
         local_dir: ${{ env.WORKING_DIRECTORY }}
         remote_dir: /www.mimascota.somee.com
         
         delete: "false"

